### PR TITLE
Remove singleton dimensions in reshape and add dropdims

### LINKED ISSUE #184: `dropdims` should be able to remove trailing 1s
Currently calling `dropdims(A, n)` on a disk array gives the error: 

`"For DiskArrays, reshape is restricted to adding singleton dimensions"`

We should define `dropdims` to just call `view` instead of `reshape` - this is what Rasters.jl does manually - but it would be nice if `dropdims` just worked.

### PR DESCRIPTION
**Pull request by meggart**
Fixes #184 @lazarusA @felixcremer

### CODE REVIEW

File: src/reshape.jl [hunk 1]
```diff
@@ -20,73 +20,85 @@ rectangles in the parent array.
...
+        if m != -1
+            indx = replace[ii]
+            inew = Base.setindex(inew, indx, m)
+        end
+    end
+    inew
+end
+
+#This is currently not type-stable, feel free to make an improved version through a PR
+function dropdims_disk(a; dims)
```
Comment (felixcremer) [inline src/reshape.jl]: Is this even necessary? 
I tested removing the Base.dropdims overload below and it still works as expected and the dropdims tests still pass. This works ,because the Base.dropdims fallback definition does some size checks and then calls rebase on the dimensions.

Comment (meggart) [reply src/reshape.jl]: Great! I removed the dropdims implementation.

**Review by felixcremer — APPROVED** [review]
LGTM
